apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tald-unia.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tald-unia.name" . }}
    helm.sh/chart: {{ include "tald-unia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/environment: {{ .Values.global.environment }}
  annotations:
    # Add checksum annotation to trigger pod restarts when secrets change
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # Add annotations for secret rotation tracking
    secret.tald.io/rotation-schedule: "30d"
    secret.tald.io/last-rotated: {{ now | date "2006-01-02T15:04:05Z07:00" }}
type: Opaque
data:
  # AES-256-GCM encryption key for sensitive data protection (32 bytes)
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}

  # Redis authentication password (32 bytes)
  REDIS_PASSWORD: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc }}

  # JWT signing secret for authentication (64 bytes)
  JWT_SECRET: {{ randAlphaNum 64 | b64enc }}

  # Fleet mesh network authentication token (64 bytes)
  FLEET_AUTH_TOKEN: {{ randAlphaNum 64 | b64enc }}

  # LiDAR processing API key (32 bytes)
  LIDAR_API_KEY: {{ randAlphaNum 32 | b64enc }}

  # Game session encryption key (32 bytes)
  GAME_SESSION_KEY: {{ randAlphaNum 32 | b64enc }}

  # Point cloud data encryption key (32 bytes)
  POINT_CLOUD_KEY: {{ randAlphaNum 32 | b64enc }}

  # Social engine authentication token (32 bytes)
  SOCIAL_AUTH_TOKEN: {{ randAlphaNum 32 | b64enc }}

  # WebSocket connection secret (32 bytes)
  WEBSOCKET_SECRET: {{ randAlphaNum 32 | b64enc }}

  # Mesh network encryption key (32 bytes)
  MESH_ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}

  # Analytics service API key (32 bytes)
  ANALYTICS_API_KEY: {{ randAlphaNum 32 | b64enc }}

  # Environment scan storage key (32 bytes)
  SCAN_STORAGE_KEY: {{ randAlphaNum 32 | b64enc }}