{{/* ServiceAccount template for TALD UNIA platform */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tald-unia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tald-unia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "security"
    app.kubernetes.io/part-of: "tald-unia"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    security.tald-unia.io/rbac-enabled: {{ .Values.global.security.rbac.enabled | quote }}
    security.tald-unia.io/environment: {{ .Values.global.environment | quote }}
    {{- if .Values.serviceAccount.additionalLabels }}
    {{- toYaml .Values.serviceAccount.additionalLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
    {{- end }}
    {{- if .Values.serviceAccount.roleType }}
    iam.tald-unia.io/role-type: {{ .Values.serviceAccount.roleType | quote }}
    {{- end }}
    security.tald-unia.io/token-expiry: {{ .Values.global.security.tokenMounting.expiry | default "24h" | quote }}
    security.tald-unia.io/last-rotation: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- if .Values.global.security.tokenMounting }}
automountServiceAccountToken: {{ .Values.global.security.tokenMounting.enabled }}
{{- else }}
automountServiceAccountToken: true
{{- end }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 2 }}
{{- end }}