# Production environment Helm values for TALD UNIA platform
# Version: 1.0.0

# Global configuration values
global:
  imageRegistry: tald-unia-prod
  imageTag: stable
  imagePullPolicy: IfNotPresent
  environment: production
  monitoring:
    enabled: true
    scrapeInterval: 15s
  security:
    tls:
      enabled: true
      provider: cert-manager
    rbac:
      enabled: true

# LiDAR Core configuration
lidarCore:
  replicaCount: 3
  image:
    repository: lidar-core
    tag: stable
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
      nvidia.com/gpu: "1"
    limits:
      cpu: "4"
      memory: 8Gi
      nvidia.com/gpu: "1"
  scanRate: 30
  resolution: 0.01
  range: 5.0
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilization: 70
    targetMemoryUtilization: 75

# Fleet Manager configuration
fleetManager:
  replicaCount: 5
  image:
    repository: fleet-manager
    tag: stable
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  meshNetwork:
    maxDevices: 32
    discoveryInterval: 5s

# Game Engine configuration
gameEngine:
  replicaCount: 3
  image:
    repository: game-engine
    tag: stable
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
      nvidia.com/gpu: "1"
    limits:
      cpu: "4"
      memory: 8Gi
      nvidia.com/gpu: "1"
  vulkan:
    enabled: true
    version: "1.3"

# Social Engine configuration
socialEngine:
  replicaCount: 5
  image:
    repository: social-engine
    tag: stable
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  websocket:
    enabled: true
    maxConnections: 5000

# Redis configuration
redis:
  architecture: replication
  auth:
    enabled: true
  master:
    persistence:
      enabled: true
      size: 50Gi
  replica:
    replicaCount: 3
    persistence:
      enabled: true
      size: 50Gi

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    retention: 30d
    scrapeInterval: 15s
  grafana:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
  elasticsearch:
    enabled: true
    replicas: 3
    persistence:
      enabled: true
      size: 100Gi

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
  hosts:
    - tald-unia.com
    - api.tald-unia.com
    - game.tald-unia.com