# Default Helm chart values for TALD UNIA platform
# Version: 1.0.0

# Global configuration values
global:
  imageRegistry: tald-unia-dev
  imageTag: latest
  imagePullPolicy: Always
  environment: development
  monitoring:
    enabled: true
    scrapeInterval: 30s
  security:
    tls:
      enabled: true
      provider: cert-manager
    rbac:
      enabled: true

# LiDAR Core configuration
lidarCore:
  replicaCount: 1
  image:
    repository: lidar-core
    tag: latest
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      nvidia.com/gpu: 1
    limits:
      cpu: 1
      memory: 2Gi
      nvidia.com/gpu: 1
  scanRate: 30
  resolution: 0.01
  range: 5.0
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 80
    targetMemoryUtilization: 85

# Fleet Manager configuration
fleetManager:
  replicaCount: 1
  image:
    repository: fleet-manager
    tag: latest
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  meshNetwork:
    maxDevices: 32
    discoveryInterval: 10s

# Game Engine configuration
gameEngine:
  replicaCount: 1
  image:
    repository: game-engine
    tag: latest
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      nvidia.com/gpu: 1
    limits:
      cpu: 1
      memory: 2Gi
      nvidia.com/gpu: 1
  vulkan:
    enabled: true
    version: "1.3"

# Social Engine configuration
socialEngine:
  replicaCount: 1
  image:
    repository: social-engine
    tag: latest
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  websocket:
    enabled: true
    maxConnections: 1000

# Redis configuration
redis:
  architecture: replication
  auth:
    enabled: true
  master:
    persistence:
      enabled: true
      size: 5Gi
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 5Gi

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    retention: 7d
    scrapeInterval: 30s
  grafana:
    enabled: true
    persistence:
      enabled: true
      size: 1Gi
  elasticsearch:
    enabled: true
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    enabled: true
  hosts:
    - dev.tald-unia.com